/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _SqlxMigrations {
  checksum: Buffer;
  description: string;
  execution_time: string;
  installed_on: Generated<string>;
  success: number;
  version: string | null;
}

export interface Identity {
  display_name: string | null;
  hostname: string;
  pid: number | null;
  pk: Generated<number>;
  process_name: string | null;
  start_ms: number | null;
  writer_id: string;
}

export interface Records {
  fields_json: string;
  id: Generated<number>;
  identity_pk: number;
  kind: number;
  level: number | null;
  marker_kind: number | null;
  marker_note: string | null;
  message: string;
  parent_id: number | null;
  received_ms: number;
  source: string | null;
  span_id: number | null;
  ts_ms: number;
}

export interface Sessions {
  connected_at: number;
  disconnected_at: number | null;
  identity_pk: number;
  last_seen_at: number;
  reason: number | null;
  session_id: string;
}

export interface DB {
  _sqlx_migrations: _SqlxMigrations;
  identity: Identity;
  records: Records;
  sessions: Sessions;
}
